[2025-03-24T16:56:52.569+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T16:56:52.597+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_eng_dag_etl.unzip_task manual__2025-03-24T16:56:34.140458+00:00 [queued]>
[2025-03-24T16:56:52.611+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_eng_dag_etl.unzip_task manual__2025-03-24T16:56:34.140458+00:00 [queued]>
[2025-03-24T16:56:52.611+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T16:56:52.625+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): unzip_task> on 2025-03-24 16:56:34.140458+00:00
[2025-03-24T16:56:52.630+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T16:56:52.630+0000] {standard_task_runner.py:72} INFO - Started process 93 to run task
[2025-03-24T16:56:52.632+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_eng_dag_etl', 'unzip_task', 'manual__2025-03-24T16:56:34.140458+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/data-eng-dag-etl/dag.py', '--cfg-path', '/tmp/tmpe10zb326']
[2025-03-24T16:56:52.634+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask unzip_task
[2025-03-24T16:56:52.701+0000] {task_command.py:467} INFO - Running <TaskInstance: data_eng_dag_etl.unzip_task manual__2025-03-24T16:56:34.140458+00:00 [running]> on host 644dbf161577
[2025-03-24T16:56:52.848+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='celulardaveve@gmail.com' AIRFLOW_CTX_DAG_OWNER='Veronica Sa' AIRFLOW_CTX_DAG_ID='data_eng_dag_etl' AIRFLOW_CTX_TASK_ID='unzip_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T16:56:34.140458+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T16:56:34.140458+00:00'
[2025-03-24T16:56:52.850+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T16:56:52.871+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-03-24T16:56:52.871+0000] {connection.py:424} INFO - Snowflake Connector for Python Version: 3.13.2, Python Version: 3.12.9, Platform: Linux-6.8.0-52-generic-x86_64-with-glibc2.36
[2025-03-24T16:56:52.872+0000] {connection.py:1213} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-24T16:56:52.872+0000] {connection.py:1295} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-24T16:56:54.678+0000] {sql.py:511} INFO - Running statement: COPY INTO CANDIDATE_00184.FLIGHTS
        FROM @PUBLIC.S3_FOLDER/flights.gz
        FILE_FORMAT = csv_format;, parameters: None
[2025-03-24T16:57:09.608+0000] {sql.py:520} INFO - Rows affected: 1
[2025-03-24T16:57:09.609+0000] {snowflake.py:477} INFO - Rows affected: 1
[2025-03-24T16:57:09.609+0000] {snowflake.py:478} INFO - Snowflake query id: 01bb39d8-0907-c6ea-006a-f2030076e0d6
[2025-03-24T16:57:10.223+0000] {connection.py:803} INFO - closed
[2025-03-24T16:57:10.529+0000] {connection.py:809} INFO - No async queries seem to be running, deleting session
[2025-03-24T16:57:10.838+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-24T16:57:10.860+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T16:57:10.861+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_eng_dag_etl, task_id=unzip_task, run_id=manual__2025-03-24T16:56:34.140458+00:00, execution_date=20250324T165634, start_date=20250324T165652, end_date=20250324T165710
[2025-03-24T16:57:10.966+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T16:57:10.997+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-24T16:57:11.001+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
