[2025-03-07T18:42:50.734+0000] {processor.py:186} INFO - Started process (PID=334) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:42:50.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:42:50.736+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:42:50.736+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:42:50.756+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:42:50.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:42:50.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:42:50.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.042 seconds
[2025-03-07T18:43:21.035+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:43:21.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:43:21.039+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:43:21.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:43:21.051+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:43:21.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:43:21.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:43:21.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.047 seconds
[2025-03-07T18:43:51.346+0000] {processor.py:186} INFO - Started process (PID=351) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:43:51.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:43:51.352+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:43:51.351+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:43:51.361+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:43:51.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:43:51.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:43:51.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.041 seconds
[2025-03-07T18:44:21.643+0000] {processor.py:186} INFO - Started process (PID=359) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:44:21.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:44:21.648+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:44:21.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:44:21.657+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:44:21.656+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:44:21.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:44:21.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.039 seconds
[2025-03-07T18:44:51.934+0000] {processor.py:186} INFO - Started process (PID=367) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:44:51.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:44:51.938+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:44:51.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:44:51.948+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:44:51.947+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:44:51.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:44:51.969+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.044 seconds
[2025-03-07T18:45:22.252+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:45:22.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:45:22.256+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:45:22.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:45:22.261+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:45:22.260+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:45:22.262+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:45:22.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.038 seconds
[2025-03-07T18:45:52.541+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:45:52.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:45:52.546+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:45:52.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:45:52.552+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:45:52.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:45:52.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:45:52.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.034 seconds
[2025-03-07T18:46:22.803+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:46:22.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:46:22.808+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:46:22.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:46:22.813+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:46:22.812+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:46:22.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:46:22.834+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.041 seconds
[2025-03-07T18:46:53.095+0000] {processor.py:186} INFO - Started process (PID=399) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:46:53.098+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:46:53.101+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:46:53.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:46:53.111+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:46:53.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:46:53.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:46:53.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.045 seconds
[2025-03-07T18:47:23.370+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:47:23.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:47:23.375+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:47:23.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:47:23.381+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:47:23.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:47:23.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:47:23.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.047 seconds
[2025-03-07T18:47:53.675+0000] {processor.py:186} INFO - Started process (PID=415) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:47:53.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:47:53.679+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:47:53.679+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:47:53.685+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:47:53.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:47:53.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:47:53.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.042 seconds
[2025-03-07T18:48:23.961+0000] {processor.py:186} INFO - Started process (PID=423) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:48:23.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:48:23.968+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:48:23.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:48:23.976+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:48:23.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:48:23.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:48:24.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.050 seconds
[2025-03-07T18:48:54.241+0000] {processor.py:186} INFO - Started process (PID=430) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:48:54.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:48:54.246+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:48:54.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:48:54.255+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:48:54.253+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:48:54.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:48:54.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.038 seconds
[2025-03-07T18:49:24.527+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:49:24.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:49:24.532+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:49:24.531+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:49:24.537+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:49:24.536+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:49:24.537+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:49:24.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.037 seconds
[2025-03-07T18:49:54.807+0000] {processor.py:186} INFO - Started process (PID=446) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:49:54.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:49:54.812+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:49:54.812+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:49:54.818+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:49:54.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:49:54.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:49:54.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.039 seconds
[2025-03-07T18:50:25.095+0000] {processor.py:186} INFO - Started process (PID=454) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:50:25.099+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:50:25.100+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:50:25.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:50:25.107+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:50:25.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:50:25.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:50:25.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.043 seconds
[2025-03-07T18:50:55.399+0000] {processor.py:186} INFO - Started process (PID=461) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:50:55.402+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:50:55.404+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:50:55.404+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:50:55.412+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:50:55.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:50:55.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:50:55.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.055 seconds
[2025-03-07T18:51:25.705+0000] {processor.py:186} INFO - Started process (PID=469) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:51:25.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:51:25.710+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:51:25.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:51:25.719+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:51:25.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:51:25.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:51:25.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.039 seconds
[2025-03-07T18:51:56.011+0000] {processor.py:186} INFO - Started process (PID=476) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:51:56.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:51:56.015+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:51:56.015+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:51:56.023+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:51:56.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:51:56.024+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:51:56.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.042 seconds
[2025-03-07T18:52:26.273+0000] {processor.py:186} INFO - Started process (PID=484) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:52:26.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:52:26.278+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:52:26.278+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:52:26.287+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:52:26.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:52:26.288+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:52:26.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.045 seconds
[2025-03-07T18:52:56.560+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:52:56.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:52:56.565+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:52:56.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:52:56.571+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:52:56.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:52:56.572+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:52:56.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.045 seconds
[2025-03-07T18:53:26.876+0000] {processor.py:186} INFO - Started process (PID=501) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:53:26.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:53:26.882+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:53:26.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:53:26.889+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:53:26.888+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:53:26.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:53:26.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.048 seconds
[2025-03-07T18:53:57.168+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:53:57.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:53:57.172+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:53:57.172+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:53:57.178+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:53:57.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:53:57.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:53:57.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.044 seconds
[2025-03-07T18:54:27.489+0000] {processor.py:186} INFO - Started process (PID=519) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:54:27.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:54:27.495+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:54:27.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:54:27.503+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:54:27.502+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:54:27.503+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:54:27.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.052 seconds
[2025-03-07T18:54:57.762+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:54:57.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:54:57.768+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:54:57.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:54:57.776+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:54:57.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:54:57.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:54:57.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.040 seconds
[2025-03-07T18:55:28.067+0000] {processor.py:186} INFO - Started process (PID=537) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:55:28.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:55:28.072+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:55:28.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:55:28.078+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:55:28.077+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:55:28.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:55:28.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.038 seconds
[2025-03-07T18:55:58.359+0000] {processor.py:186} INFO - Started process (PID=546) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:55:58.362+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:55:58.365+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:55:58.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:55:58.373+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:55:58.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:55:58.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:55:58.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.049 seconds
[2025-03-07T18:56:28.673+0000] {processor.py:186} INFO - Started process (PID=555) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:56:28.675+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:56:28.676+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:56:28.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:56:28.686+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:56:28.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:56:28.686+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:56:28.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.050 seconds
[2025-03-07T18:56:58.974+0000] {processor.py:186} INFO - Started process (PID=564) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:56:58.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:56:58.979+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:56:58.979+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:56:58.986+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:56:58.985+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:56:58.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:56:59.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.053 seconds
[2025-03-07T18:57:29.269+0000] {processor.py:186} INFO - Started process (PID=573) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:57:29.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:57:29.271+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:57:29.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:57:29.280+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:57:29.279+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:57:29.280+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:57:29.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.034 seconds
[2025-03-07T18:57:59.544+0000] {processor.py:186} INFO - Started process (PID=582) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:57:59.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:57:59.549+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:57:59.549+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:57:59.558+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:57:59.557+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:57:59.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:57:59.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.040 seconds
[2025-03-07T18:58:29.834+0000] {processor.py:186} INFO - Started process (PID=591) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:58:29.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:58:29.837+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:58:29.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:58:29.845+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:58:29.844+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:58:29.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:58:29.871+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.044 seconds
[2025-03-07T18:59:00.140+0000] {processor.py:186} INFO - Started process (PID=600) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:59:00.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:59:00.146+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:59:00.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:59:00.152+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:59:00.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:59:00.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:59:00.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.039 seconds
[2025-03-07T18:59:30.422+0000] {processor.py:186} INFO - Started process (PID=609) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:59:30.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T18:59:30.423+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:59:30.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:59:30.429+0000] {logging_mixin.py:190} INFO - [2025-03-07T18:59:30.428+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T18:59:30.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T18:59:30.448+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.031 seconds
[2025-03-07T19:00:00.669+0000] {processor.py:186} INFO - Started process (PID=618) to work on /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T19:00:00.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/check-dag-status/check_dag.py for tasks to queue
[2025-03-07T19:00:00.672+0000] {logging_mixin.py:190} INFO - [2025-03-07T19:00:00.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T19:00:00.677+0000] {logging_mixin.py:190} INFO - [2025-03-07T19:00:00.676+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/check-dag-status/check_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/check-dag-status/check_dag.py", line 17, in <module>
    C = import_module("check-dag-status-etl.check_dags_constants")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-dag-status-etl'
[2025-03-07T19:00:00.678+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/check-dag-status/check_dag.py
[2025-03-07T19:00:00.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/check-dag-status/check_dag.py took 0.035 seconds
