[2025-03-24T15:28:53.149+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-24T15:28:53.178+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_eng_dag_etl.creating_ddl_task manual__2025-03-24T15:28:48.648931+00:00 [queued]>
[2025-03-24T15:28:53.191+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_eng_dag_etl.creating_ddl_task manual__2025-03-24T15:28:48.648931+00:00 [queued]>
[2025-03-24T15:28:53.191+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-24T15:28:53.207+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): creating_ddl_task> on 2025-03-24 15:28:48.648931+00:00
[2025-03-24T15:28:53.217+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-24T15:28:53.219+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2025-03-24T15:28:53.219+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_eng_dag_etl', 'creating_ddl_task', 'manual__2025-03-24T15:28:48.648931+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/data-eng-dag-etl/dag.py', '--cfg-path', '/tmp/tmpd4aom344']
[2025-03-24T15:28:53.222+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask creating_ddl_task
[2025-03-24T15:28:53.267+0000] {task_command.py:467} INFO - Running <TaskInstance: data_eng_dag_etl.creating_ddl_task manual__2025-03-24T15:28:48.648931+00:00 [running]> on host 9667951f056a
[2025-03-24T15:28:53.346+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='celulardaveve@gmail.com' AIRFLOW_CTX_DAG_OWNER='Veronica Sa' AIRFLOW_CTX_DAG_ID='data_eng_dag_etl' AIRFLOW_CTX_TASK_ID='creating_ddl_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T15:28:48.648931+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T15:28:48.648931+00:00'
[2025-03-24T15:28:53.347+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-24T15:28:53.391+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-03-24T15:28:53.392+0000] {connection.py:424} INFO - Snowflake Connector for Python Version: 3.13.2, Python Version: 3.12.9, Platform: Linux-6.8.0-52-generic-x86_64-with-glibc2.36
[2025-03-24T15:28:53.395+0000] {connection.py:1213} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-24T15:28:53.396+0000] {connection.py:1295} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-24T15:28:59.386+0000] {sql.py:511} INFO - Running statement: SELECT 
        column_name
    FROM TABLE(
    INFER_SCHEMA(
      LOCATION=>'@RECRUITMENT_DB.PUBLIC.S3_FOLDER/flights.gz'
      , FILE_FORMAT=>'my_csv_format'
      )
    );, parameters: None
[2025-03-24T15:29:40.144+0000] {sql.py:520} INFO - Rows affected: 31
[2025-03-24T15:29:40.146+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/snowflake/hooks/snowflake.py:468: DeprecationWarning: Import of fetch_all_handler from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
  result = self._make_common_data_structure(handler(cur))  # type: ignore[attr-defined]

[2025-03-24T15:29:40.156+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/snowflake/hooks/snowflake.py:469: DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
  if return_single_query_results(sql, return_last, split_statements):

[2025-03-24T15:29:40.161+0000] {snowflake.py:477} INFO - Rows affected: 31
[2025-03-24T15:29:40.162+0000] {snowflake.py:478} INFO - Snowflake query id: 01bb3980-0907-dcc6-006a-f2030076d00e
[2025-03-24T15:29:40.445+0000] {connection.py:803} INFO - closed
[2025-03-24T15:29:40.698+0000] {connection.py:809} INFO - No async queries seem to be running, deleting session
[2025-03-24T15:29:40.971+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/snowflake/hooks/snowflake.py:487: DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
  if return_single_query_results(sql, return_last, split_statements):

[2025-03-24T15:29:40.975+0000] {logging_mixin.py:190} INFO - [('c1',), ('c2',), ('c3',), ('c4',), ('c5',), ('c6',), ('c7',), ('c8',), ('c9',), ('c10',), ('c11',), ('c12',), ('c13',), ('c14',), ('c15',), ('c16',), ('c17',), ('c18',), ('c19',), ('c20',), ('c21',), ('c22',), ('c23',), ('c24',), ('c25',), ('c26',), ('c27',), ('c28',), ('c29',), ('c30',), ('c31',)]
[2025-03-24T15:29:40.977+0000] {logging_mixin.py:190} INFO - ['c1']
[2025-03-24T15:29:40.979+0000] {logging_mixin.py:190} INFO - CREATE OR REPLACE TABLE flights (
    c1 VARCHAR
);
[2025-03-24T15:29:40.980+0000] {connection.py:424} INFO - Snowflake Connector for Python Version: 3.13.2, Python Version: 3.12.9, Platform: Linux-6.8.0-52-generic-x86_64-with-glibc2.36
[2025-03-24T15:29:40.983+0000] {connection.py:1213} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-24T15:29:40.984+0000] {connection.py:1295} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-24T15:29:42.459+0000] {sql.py:511} INFO - Running statement: CREATE OR REPLACE TABLE flights (
    c1 VARCHAR
);, parameters: None
[2025-03-24T15:29:43.011+0000] {sql.py:520} INFO - Rows affected: 1
[2025-03-24T15:29:43.012+0000] {snowflake.py:477} INFO - Rows affected: 1
[2025-03-24T15:29:43.013+0000] {snowflake.py:478} INFO - Snowflake query id: 01bb3981-0907-dcc6-006a-f2030076d012
[2025-03-24T15:29:43.371+0000] {connection.py:803} INFO - closed
[2025-03-24T15:29:43.636+0000] {connection.py:809} INFO - No async queries seem to be running, deleting session
[2025-03-24T15:29:43.928+0000] {python.py:240} INFO - Done. Returned value was: CREATE OR REPLACE TABLE flights (
    c1 VARCHAR
);
[2025-03-24T15:29:43.994+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-24T15:29:43.995+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_eng_dag_etl, task_id=creating_ddl_task, run_id=manual__2025-03-24T15:28:48.648931+00:00, execution_date=20250324T152848, start_date=20250324T152853, end_date=20250324T152943
[2025-03-24T15:29:44.090+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-24T15:29:44.158+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-24T15:29:44.163+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
